apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-express-hello-world-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-express-hello-world
  template:
    metadata:
      labels:
        app: k8s-express-hello-world
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: k8s-express-hello-world
          image: gryphon2411/k8s-express-hello-world:latest
          ports:
            - containerPort: 3000